@HttpFilesSAmpleApplication_HostAddress = https://localhost:7188

GET {{HttpFilesSAmpleApplication_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{HttpFilesSAmpleApplication_HostAddress}}/api/values
Content-Type: application/json

"Test"

###
